working lora and neopixel threads

diff --git a/zephyr/justfile b/zephyr/justfile
--- a/zephyr/justfile
+++ b/zephyr/justfile
@@ -2,10 +2,18 @@ build:
     west build -b rpi_pico ./app
 
 upload:
+    #!/usr/bin/env bash
     picotool load -v -x build/zephyr/zephyr.uf2 -f
-
-monitor:
     sleep 2
-    cat /dev/ttyACM0
-        
-run: build upload monitor
+
+connect:
+    #!/usr/bin/env bash
+    VID="2e8a"
+    DEV=$(ls /dev/ttyACM* 2>/dev/null | while read d; do
+        if lsusb | grep -q "$VID"; then
+            echo "$d";  break;
+        fi
+    done)
+    minicom -D "$DEV" || echo "Device not found"
+
+run: build upload connect
